rm /data/data/com.termux/files/usr/bin/leer
rm /data/data/com.termux/files/usr/bin/actualizar-paquetes
rm /data/data/com.termux/files/usr/bin/arbol
rm /data/data/com.termux/files/usr/bin/atras
rm /data/data/com.termux/files/usr/bin/calendario
rm /data/data/com.termux/files/usr/bin/clonar
rm /data/data/com.termux/files/usr/bin/copiar
rm /data/data/com.termux/files/usr/bin/crear-archivo
rm /data/data/com.termux/files/usr/bin/crear-carpeta
rm /data/data/com.termux/files/usr/bin/desencriptar
rm /data/data/com.termux/files/usr/bin/estoy
rm /data/data/com.termux/files/usr/bin/dormir
rm /data/data/com.termux/files/usr/bin/editar
rm /data/data/com.termux/files/usr/bin/eliminar-archivo
rm /data/data/com.termux/files/usr/bin/eliminar-permiso
rm /data/data/com.termux/files/usr/bin/eliminar-carpeta
rm /data/data/com.termux/files/usr/bin/encriptar
rm /data/data/com.termux/files/usr/bin/home
rm /data/data/com.termux/files/usr/bin/info-web
rm /data/data/com.termux/files/usr/bin/instalar
rm /data/data/com.termux/files/usr/bin/instalar-web
rm /data/data/com.termux/files/usr/bin/limpiar
rm /data/data/com.termux/files/usr/bin/lista
rm /data/data/com.termux/files/usr/bin/matar-proceso
rm /data/data/com.termux/files/usr/bin/mover
rm /data/data/com.termux/files/usr/bin/paquetes-instalados
rm /data/data/com.termux/files/usr/bin/permiso-total
rm /data/data/com.termux/files/usr/bin/procesos
rm /data/data/com.termux/files/usr/bin/salir
rm /data/data/com.termux/files/usr/bin/ver
rm /data/data/com.termux/files/usr/bin/ver-carpeta