chmod 777 /data/data/com.termux/files/usr/bin/leer
chmod 777 /data/data/com.termux/files/usr/bin/actualizar-paquetes
chmod 777 /data/data/com.termux/files/usr/bin/arbol
chmod 777 /data/data/com.termux/files/usr/bin/atras
chmod 777 /data/data/com.termux/files/usr/bin/calendario
chmod 777 /data/data/com.termux/files/usr/bin/clonar
chmod 777 /data/data/com.termux/files/usr/bin/copiar
chmod 777 /data/data/com.termux/files/usr/bin/crear-archivo
chmod 777 /data/data/com.termux/files/usr/bin/crear-carpeta
chmod 777 /data/data/com.termux/files/usr/bin/desencriptar
chmod 777 /data/data/com.termux/files/usr/bin/estoy
chmod 777 /data/data/com.termux/files/usr/bin/dormir
chmod 777 /data/data/com.termux/files/usr/bin/editar
chmod 777 /data/data/com.termux/files/usr/bin/eliminar-archivo
chmod 777 /data/data/com.termux/files/usr/bin/eliminar-permiso
chmod 777 /data/data/com.termux/files/usr/bin/eliminar-carpeta
chmod 777 /data/data/com.termux/files/usr/bin/encriptar
chmod 777 /data/data/com.termux/files/usr/bin/home
chmod 777 /data/data/com.termux/files/usr/bin/info-web
chmod 777 /data/data/com.termux/files/usr/bin/instalar
chmod 777 /data/data/com.termux/files/usr/bin/instalar-web
chmod 777 /data/data/com.termux/files/usr/bin/limpiar
chmod 777 /data/data/com.termux/files/usr/bin/lista
chmod 777 /data/data/com.termux/files/usr/bin/matar-proceso
chmod 777 /data/data/com.termux/files/usr/bin/mover
chmod 777 /data/data/com.termux/files/usr/bin/paquetes-instalados
chmod 777 /data/data/com.termux/files/usr/bin/permiso-total
chmod 777 /data/data/com.termux/files/usr/bin/procesos
chmod 777 /data/data/com.termux/files/usr/bin/salir
chmod 777 /data/data/com.termux/files/usr/bin/ver
chmod 777 /data/data/com.termux/files/usr/bin/ver-carpeta
chmod 777 /data/data/com.termux/files/usr/bin/man-actualizar-paquetes
chmod 777 /data/data/com.termux/files/usr/bin/man-arbol
chmod 777 /data/data/com.termux/files/usr/bin/man-instalar-web
chmod 777 /data/data/com.termux/files/usr/bin/man-leer
chmod 777 /data/data/com.termux/files/usr/bin/man-limpiar
chmod 777 /data/data/com.termux/files/usr/bin/man-matar-proceso
chmod 777 /data/data/com.termux/files/usr/bin/man-mover
chmod 777 /data/data/com.termux/files/usr/bin/man-paquetes-instalados
chmod 777 /data/data/com.termux/files/usr/bin/man-permiso-total
chmod 777 /data/data/com.termux/files/usr/bin/man-procesos
chmod 777 /data/data/com.termux/files/usr/bin/man-ver
chmod 777 /data/data/com.termux/files/usr/bin/man-ver-carpeta
chmod 777 /data/data/com.termux/files/usr/bin/man-matar-proceso
chmod 777 /data/data/com.termux/files/usr/bin/man-clonar
chmod 777 /data/data/com.termux/files/usr/bin/man-atras
chmod 777 /data/data/com.termux/files/usr/bin/man-copiar
chmod 777 /data/data/com.termux/files/usr/bin/man-crear-archivo
chmod 777 /data/data/com.termux/files/usr/bin/man-instalar
chmod 777 /data/data/com.termux/files/usr/bin/man-info-web
chmod 777 /data/data/com.termux/files/usr/bin/man-encriptar
chmod 777 /data/data/com.termux/files/usr/bin/man-eliminar-carpeta
chmod 777 /data/data/com.termux/files/usr/bin/man-editar
chmod 777 /data/data/com.termux/files/usr/bin/man-eliminar-carpeta
chmod 777 /data/data/com.termux/files/usr/bin/man-crear-carpeta
chmod 777 /data/data/com.termux/files/usr/bin/man-desencriptar